PREFIX          = ../..
NEEDSFROMDIRS 	= ../logics ../omstd
BUTFILES 	= catalogue.omdoc
CSS		= css='../omstd/omdoccd.css'
MOZONLY		= mozonly='yes'
TERMINATE	= terminate='no'

include $(PREFIX)/lib/Makefile.vars

all:		prep 4 i html ps mml

include $(PREFIX)/lib/Makefile.general
