PREFIX          = ../..
COLLFILES       = collection.omdoc
BUTFILES 	= catalogue.omdoc pvs.omdoc 
include $(PREFIX)/lib/Makefile.vars

all:		4 i html ps mml 
collection:	collection.html collection.xml collection.ps
include $(PREFIX)/lib/Makefile.general
