PREFIX          = ../..
NEEDSFROMDIRS 	= ../logics ../omstd
BUTFILES 	= catalogue.omdoc
TERMINATE	= terminate='no'

include $(PREFIX)/lib/Makefile.vars

all:		prep 4 i html ps mml 

include $(PREFIX)/lib/Makefile.general
